### ISSUE TITLE
package.json missing build script

### ISSUE THREAD

**Issue by jimk-osu** [BigstickCarpet/swagger-cli#14]
Per Contributing section of README.md `npm run build`, `build`  is not present in [package.json](https://raw.githubusercontent.com/BigstickCarpet/swagger-cli/master/package.json):
```json
scripts": {
    "lint": "eslint bin lib test --fix",
    "test": "mocha && npm run lint",
    "upgrade": "npm-check -u",
    "bump": "bump --prompt --tag --push --all",
    "release": "npm run upgrade && npm test && npm run bump && npm publish"
  }
```

Possible mismatch of desired command in README?

**Comment by BigstickCarpet** [comment]
Fixed.  Thanks for reporting
