### ISSUE TITLE
Support for OpenAPI 3.0

### ISSUE THREAD

**Issue by shreyas-agnihotri** [BigstickCarpet/swagger-cli#16]
Seems like openapi 3.0 isn't supported yet. Any plans for adding this support?

**Comment by BigstickCarpet** [comment]
Yes, I plan on adding OpenAPI 3.0 support to [Swagger Parser](https://github.com/BigstickCarpet/swagger-parser) soon, which is the library that powers Swagger CLI

**Comment by wreulicke** [comment]
@BigstickCarpet there are any progress?

**Comment by BigstickCarpet** [comment]
Oh crap.  Sorry that I forgot to update/close this issue.   I released Swagger-CLI 2.0.0 about a month ago, which [adds support for OpenAPI 3.0](https://github.com/BigstickCarpet/swagger-cli/compare/v1.0.2...v2.0.0)
