### ISSUE TITLE
swagger serve

### ISSUE THREAD

**Issue by JamieMason** [BigstickCarpet/swagger-cli#3]
Hi @BigstickCarpet,
Thanks for this great project. I just wanted to ask if you know roughly when `swagger serve` might become available for use?

Thanks a lot,

Jamie

**Comment by BigstickCarpet** [comment]
To be honest, it's probably going to be several weeks at least.  I recently started a new job, which has been keeping me **super busy**, so my personal time has been at a premium lately.  I'm currently out of the country on a business trip, but I hope to be able to make some headway on this - and all of my swagger projects - when I get back home.

**Comment by JamieMason** [comment]
No problem at all, thanks for the update.
