### ISSUE TITLE
conflict with bin name and swagger-node

### ISSUE THREAD

**Issue by dusty** [BigstickCarpet/swagger-cli#5]
The swagger-node package uses swagger for one of its bin commands, which conflicts with this one.  Causes an issue if you install both globally.

https://raw.githubusercontent.com/swagger-api/swagger-node/master/package.json

**Comment by hc-romens** [comment]
Yes, I met the exact same problem for naming conflict. 

How about change to swagger-cli?

**Comment by BigstickCarpet** [comment]
Yep.  Good point.  I'll change the command name in the next release.
