### ISSUE TITLE
Allow `parameters` to be null

### ISSUE THREAD

**Issue by jdevera** [BigstickCarpet/swagger-cli#8]
Some of our API methods take no parameters, and we used to have this as:

``` yaml
parameters:
```

 in a YAML file. After using `swagger-cli` to validate we were forced to write this:

``` yaml
parameters: []
```

Is this mandatory or this a tool specific behaviour? If the latter, can it be changed to be a bit more permissive?

**Comment by BigstickCarpet** [comment]
Hi.  Thanks for the bug report, but I'm not able to reproduce it.  For example, the following Swagger file validates fine for me:

**my-api.yaml**
```yaml
swagger: '2.0'

info:
  version: "0.0.0"
  title: Hello World

paths:
  /hello:
    get:
      responses:
        200:
          description: hello world
```

**bash**
```bash
> swagger validate my-api.yaml 
> my-api.yaml is valid
```

**Comment by BigstickCarpet** [comment]
Swagger CLI uses [Swagger Parser](https://github.com/BigstickCarpet/swagger-parser) to do its validation.  So any Swagger file that validates successfully [here](http://bigstickcarpet.com/swagger-parser/www/index.html) will also pass Swagger CLI

**Comment by jdevera** [comment]
This one fails, though:

```yaml
swagger: '2.0'

info:
  version: "0.0.0"
  title: Hello World

paths:
  /hello:
    get:
      parameters:
      responses:
        200:
          description: hello world
```

```bash
$ swagger validate test.yaml

SyntaxError: Swagger schema validation failed.
  Expected type array but found type null at #/paths//hello/get/parameters

JSON_OBJECT_VALIDATION_FAILED
    at Function.ono [as syntax] (/home/jdevera/node_modules/ono/lib/index.js:67:20)
    at validateSchema (/home/jdevera/node_modules/swagger-parser/lib/validate-schema.js:29:15)
    at /home/jdevera/node_modules/swagger-parser/lib/index.js:144:9

z-schema validation error: JSON_OBJECT_VALIDATION_FAILED
    at ZSchema.getLastError (/home/jdevera/node_modules/z-schema/src/ZSchema.js:221:13)
    at validateSchema (/home/jdevera/node_modules/swagger-parser/lib/validate-schema.js:27:23)
    at /home/jdevera/node_modules/swagger-parser/lib/index.js:144:9
```

**Comment by BigstickCarpet** [comment]
@jdevera - In YAML, a key without a value gets the value `null` (test it [here](https://yaml-online-parser.appspot.com/)).  `null` is not a valid value for the `parameters` key in Swagger, per the [Swagger 2.0 schema](https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v2.0/schema.json#L194-L200), hence the error message _"Expected type array but found type null"_.

So you need to either set the `parameters` key to an empty array (e.g. `parameters: []`) or just leave the `parameters` key off altogether.
